import ConditionalEntropy.FiniteChannelAlgebra
import ConditionalEntropy.FiniteSemiringQuotient

/-!
# The generated conditional-majorization preorder

This module places the finite conditional channels on the closed quotient
semiring.  A generator is one unnormalised conditional mixing channel on a
fixed row alphabet.  The order is the least reflexive, transitive relation
containing those generators and closed under direct sum and tensor product.

Defining the closure explicitly has two useful consequences: quotient
representatives may be relabelled or zero-extended without any choices, and
the preordered-semiring compatibility laws are derivable rather than assumed.
`FiniteChannelAlgebra.lean` proves that every aligned fixed-row path composes
to one `CMData` and that compatibility generators are themselves concrete
channels.  At quotient level, a path may choose two different representatives
of its intermediate class; collapsing that final path to one `CMData` needs a
representative-transport/common-zero-extension theorem.  The exact achieved
normal form and this remaining interface are stated below.
-/

namespace ConditionalEntropy

universe u

/-- Package a concrete nonnegative matrix as a closed semiring
representative. -/
def finiteJointRepOfCone {X Y : Type u} [Fintype X] [Fintype Y]
    (P : JointCone X Y) : FiniteJointRep.{u} where
  X := X
  Y := Y
  fintypeX := inferInstance
  fintypeY := inferInstance
  matrix := P

theorem finiteJointRepOfCone_matrix (P : FiniteJointRep.{u}) :
    finiteJointRepOfCone P.matrix = P := by
  cases P
  rfl

/-- A single concrete manuscript channel whose source and target represent
the indicated quotient elements.  Both matrices use exactly the same row
alphabet, as required by `CMData`. -/
structure ConcreteChannelWitness
    (a b : ConditionalSemiring.{u}) where
  X : Type u
  Y : Type u
  Y' : Type u
  fintypeX : Fintype X
  fintypeY : Fintype Y
  fintypeY' : Fintype Y'
  P : JointCone X Y
  Q : JointCone X Y'
  source_eq : ConditionalSemiring.mk (finiteJointRepOfCone P) = a
  target_eq : ConditionalSemiring.mk (finiteJointRepOfCone Q) = b
  rel : CMRelCone P Q

attribute [instance] ConcreteChannelWitness.fintypeX
  ConcreteChannelWitness.fintypeY ConcreteChannelWitness.fintypeY'

/-- Existence of a single concrete channel between representatives. -/
def ConcreteChannelComparison
    (a b : ConditionalSemiring.{u}) : Prop :=
  Nonempty (ConcreteChannelWitness a b)

/-- The quotient-semiring element represented by a normalized joint
distribution. -/
def conditionalSemiringOfJointProb
    {X Y : Type u} [Fintype X] [Fintype Y] (P : JointProb X Y) :
    ConditionalSemiring.{u} :=
  ConditionalSemiring.mk (finiteJointRepOfCone (jointProbToCone P))

/-- One generating comparison, closed under the two semiring operations. -/
inductive ConditionalOrderGenerator :
    ConditionalSemiring.{u} → ConditionalSemiring.{u} → Prop
  | channel {X Y Y' : Type u} [Fintype X] [Fintype Y] [Fintype Y']
      (P : JointCone X Y) (Q : JointCone X Y') (h : CMRelCone P Q) :
      ConditionalOrderGenerator
        (ConditionalSemiring.mk (finiteJointRepOfCone P))
        (ConditionalSemiring.mk (finiteJointRepOfCone Q))
  | add_right {a b : ConditionalSemiring.{u}}
      (h : ConditionalOrderGenerator a b) (c : ConditionalSemiring.{u}) :
      ConditionalOrderGenerator (a + c) (b + c)
  | mul_right {a b : ConditionalSemiring.{u}}
      (h : ConditionalOrderGenerator a b) (c : ConditionalSemiring.{u}) :
      ConditionalOrderGenerator (a * c) (b * c)

/-- The least compatible preorder generated by finite conditional mixing. -/
def ConditionalSemiringLE (a b : ConditionalSemiring.{u}) : Prop :=
  Relation.ReflTransGen ConditionalOrderGenerator a b

instance conditionalSemiringPreorder : Preorder ConditionalSemiring.{u} where
  le := ConditionalSemiringLE
  le_refl _ := Relation.ReflTransGen.refl
  le_trans _ _ _ := Relation.ReflTransGen.trans

/-- Every concrete conditional channel gives a comparison in the closed
semiring. -/
theorem finiteChannel_le {X Y Y' : Type u}
    [Fintype X] [Fintype Y] [Fintype Y']
    {P : JointCone X Y} {Q : JointCone X Y'} (h : CMRelCone P Q) :
    ConditionalSemiring.mk (finiteJointRepOfCone P) ≤
      ConditionalSemiring.mk (finiteJointRepOfCone Q) :=
  Relation.ReflTransGen.tail Relation.ReflTransGen.refl
    (ConditionalOrderGenerator.channel P Q h)

theorem concreteChannelComparison_of_cmRelCone
    {X Y Y' : Type u} [Fintype X] [Fintype Y] [Fintype Y']
    {P : JointCone X Y} {Q : JointCone X Y'} (h : CMRelCone P Q) :
    ConcreteChannelComparison
      (ConditionalSemiring.mk (finiteJointRepOfCone P))
      (ConditionalSemiring.mk (finiteJointRepOfCone Q)) :=
  ⟨{ X := X
     Y := Y
     Y' := Y'
     fintypeX := inferInstance
     fintypeY := inferInstance
     fintypeY' := inferInstance
     P := P
     Q := Q
     source_eq := rfl
     target_eq := rfl
     rel := h }⟩

/-- Every compatibility generator is realized by one concrete channel after
choosing representatives for the untouched semiring factor. -/
theorem ConditionalOrderGenerator.concreteChannelComparison
    {a b : ConditionalSemiring.{u}} (h : ConditionalOrderGenerator a b) :
    ConcreteChannelComparison a b := by
  induction h with
  | channel P Q hPQ =>
      exact concreteChannelComparison_of_cmRelCone hPQ
  | add_right h c ih =>
      induction c using Quot.ind with
      | _ R =>
        rcases ih with ⟨⟨X, Y, Y', fX, fY, fY', P, Q, ha, hb, hPQ⟩⟩
        letI : Fintype X := fX
        letI : Fintype Y := fY
        letI : Fintype Y' := fY'
        refine ⟨
          { X := Sum X R.X
            Y := Sum Y R.Y
            Y' := Sum Y' R.Y
            fintypeX := inferInstance
            fintypeY := inferInstance
            fintypeY' := inferInstance
            P := jointConeDirectSum P R.matrix
            Q := jointConeDirectSum Q R.matrix
            source_eq := ?_
            target_eq := ?_
            rel := hPQ.directSum (CMRelCone.refl R.matrix) }⟩
        · change ConditionalSemiring.mk
              (finiteJointAdd (finiteJointRepOfCone P)
                (finiteJointRepOfCone R.matrix)) =
            _ + ConditionalSemiring.mk R
          rw [← ConditionalSemiring.mk_add, ha, finiteJointRepOfCone_matrix]
        · change ConditionalSemiring.mk
              (finiteJointAdd (finiteJointRepOfCone Q)
                (finiteJointRepOfCone R.matrix)) =
            _ + ConditionalSemiring.mk R
          rw [← ConditionalSemiring.mk_add, hb, finiteJointRepOfCone_matrix]
  | mul_right h c ih =>
      induction c using Quot.ind with
      | _ R =>
        rcases ih with ⟨⟨X, Y, Y', fX, fY, fY', P, Q, ha, hb, hPQ⟩⟩
        letI : Fintype X := fX
        letI : Fintype Y := fY
        letI : Fintype Y' := fY'
        refine ⟨
          { X := X × R.X
            Y := Y × R.Y
            Y' := Y' × R.Y
            fintypeX := inferInstance
            fintypeY := inferInstance
            fintypeY' := inferInstance
            P := jointConeTensor P R.matrix
            Q := jointConeTensor Q R.matrix
            source_eq := ?_
            target_eq := ?_
            rel := hPQ.tensor (CMRelCone.refl R.matrix) }⟩
        · change ConditionalSemiring.mk
              (finiteJointMul (finiteJointRepOfCone P)
                (finiteJointRepOfCone R.matrix)) =
            _ * ConditionalSemiring.mk R
          rw [← ConditionalSemiring.mk_mul, ha, finiteJointRepOfCone_matrix]
        · change ConditionalSemiring.mk
              (finiteJointMul (finiteJointRepOfCone Q)
                (finiteJointRepOfCone R.matrix)) =
            _ * ConditionalSemiring.mk R
          rw [← ConditionalSemiring.mk_mul, hb, finiteJointRepOfCone_matrix]

theorem conditionalSemiring_le_of_concreteChannelComparison
    {a b : ConditionalSemiring.{u}} (h : ConcreteChannelComparison a b) :
    a ≤ b := by
  rcases h with ⟨W⟩
  calc
    a = ConditionalSemiring.mk (finiteJointRepOfCone W.P) := W.source_eq.symm
    _ ≤ ConditionalSemiring.mk (finiteJointRepOfCone W.Q) := finiteChannel_le W.rel
    _ = b := W.target_eq

/-- The quotient preorder is exactly a finite chain of single concrete
channels between quotient representatives.  This is stronger than the
original generator presentation: compatibility constructors have been
eliminated using the explicit direct-sum and tensor channel realizers. -/
theorem conditionalSemiring_le_iff_reflTransGen_concrete
    (a b : ConditionalSemiring.{u}) :
    a ≤ b ↔ Relation.ReflTransGen ConcreteChannelComparison a b := by
  constructor
  · intro h
    change Relation.ReflTransGen ConditionalOrderGenerator a b at h
    induction h with
    | refl => exact Relation.ReflTransGen.refl
    | tail h hstep ih =>
        exact Relation.ReflTransGen.tail ih hstep.concreteChannelComparison
  · intro h
    induction h with
    | refl => exact le_rfl
    | tail h hstep ih =>
        exact le_trans ih
          (conditionalSemiring_le_of_concreteChannelComparison hstep)

theorem concreteChannelComparison_refl (a : ConditionalSemiring.{u}) :
    ConcreteChannelComparison a a := by
  induction a using Quot.ind with
  | _ P =>
    refine ⟨
      { X := P.X
        Y := P.Y
        Y' := P.Y
        fintypeX := P.fintypeX
        fintypeY := P.fintypeY
        fintypeY' := P.fintypeY
        P := P.matrix
        Q := P.matrix
        source_eq := congrArg ConditionalSemiring.mk
          (finiteJointRepOfCone_matrix P)
        target_eq := congrArg ConditionalSemiring.mk
          (finiteJointRepOfCone_matrix P)
        rel := CMRelCone.refl P.matrix }⟩

/-- A precise interface for the only remaining quotient-level compression
issue.  If single-channel comparison can be transported through an arbitrary
change of representative of the intermediate quotient class, then every
generated comparison is one concrete channel.  The fixed-row theorem
`FixedRowCone.reflTransGen_cmRel_iff` supplies this transitivity when the
intermediate matrix is already aligned. -/
theorem conditionalSemiring_le_iff_concrete_of_trans
    (htrans : ∀ {a b c : ConditionalSemiring.{u}},
      ConcreteChannelComparison a b → ConcreteChannelComparison b c →
        ConcreteChannelComparison a c)
    (a b : ConditionalSemiring.{u}) :
    a ≤ b ↔ ConcreteChannelComparison a b := by
  rw [conditionalSemiring_le_iff_reflTransGen_concrete]
  constructor
  · intro h
    induction h with
    | refl => exact concreteChannelComparison_refl a
    | tail h hstep ih => exact htrans ih hstep
  · intro h
    exact Relation.ReflTransGen.tail Relation.ReflTransGen.refl h

/-- A normalized conditional channel induces the corresponding quotient
comparison. -/
theorem conditionalSemiringOfJointProb_le {X Y Y' : Type u}
    [Fintype X] [Fintype Y] [Fintype Y']
    {P : JointProb X Y} {Q : JointProb X Y'} (h : CMRel P Q) :
    conditionalSemiringOfJointProb P ≤ conditionalSemiringOfJointProb Q :=
  finiteChannel_le h.toCone

/-- Zero extension does not change the quotient-semiring element of a joint
probability matrix. -/
theorem conditionalSemiringOfJointProb_zeroExtend
    {X Y X' Y' : Type u}
    [Fintype X] [Nonempty X] [Fintype Y] [Nonempty Y]
    [Fintype X'] [Nonempty X'] [Fintype Y'] [Nonempty Y']
    (eX : X ↪ X') (eY : Y ↪ Y') (P : JointProb X Y) :
    conditionalSemiringOfJointProb (jointZeroExtend eX eY P) =
      conditionalSemiringOfJointProb P := by
  rw [conditionalSemiringOfJointProb, conditionalSemiringOfJointProb,
    jointProbToCone_jointZeroExtend]
  change ConditionalSemiring.mk
      (finiteJointZeroExtend (finiteJointRepOfCone (jointProbToCone P)) eX eY) =
    ConditionalSemiring.mk (finiteJointRepOfCone (jointProbToCone P))
  exact (Quot.sound (FiniteJointStep.zeroExtend
    (finiteJointRepOfCone (jointProbToCone P)) eX eY)).symm

/-- Addition on the right preserves the generated preorder. -/
theorem conditionalSemiring_add_le_add_right
    {a b : ConditionalSemiring.{u}} (h : a ≤ b) (c : ConditionalSemiring.{u}) :
    a + c ≤ b + c := by
  change Relation.ReflTransGen ConditionalOrderGenerator a b at h
  change Relation.ReflTransGen ConditionalOrderGenerator (a + c) (b + c)
  induction h with
  | refl => exact Relation.ReflTransGen.refl
  | tail h step ih =>
      exact Relation.ReflTransGen.tail ih
        (ConditionalOrderGenerator.add_right step c)

/-- Addition on the left preserves the generated preorder. -/
theorem conditionalSemiring_add_le_add_left
    {a b : ConditionalSemiring.{u}} (h : a ≤ b) (c : ConditionalSemiring.{u}) :
    c + a ≤ c + b := by
  calc
    c + a = a + c := add_comm _ _
    _ ≤ b + c := conditionalSemiring_add_le_add_right h c
    _ = c + b := add_comm _ _

/-- Addition is monotone in both variables. -/
theorem conditionalSemiring_add_le_add
    {a b c d : ConditionalSemiring.{u}} (hab : a ≤ b) (hcd : c ≤ d) :
    a + c ≤ b + d :=
  le_trans (conditionalSemiring_add_le_add_right hab c)
    (conditionalSemiring_add_le_add_left hcd b)

/-- Multiplication on the right preserves the generated preorder. -/
theorem conditionalSemiring_mul_le_mul_right
    {a b : ConditionalSemiring.{u}} (h : a ≤ b) (c : ConditionalSemiring.{u}) :
    a * c ≤ b * c := by
  change Relation.ReflTransGen ConditionalOrderGenerator a b at h
  change Relation.ReflTransGen ConditionalOrderGenerator (a * c) (b * c)
  induction h with
  | refl => exact Relation.ReflTransGen.refl
  | tail h step ih =>
      exact Relation.ReflTransGen.tail ih
        (ConditionalOrderGenerator.mul_right step c)

/-- Multiplication on the left preserves the generated preorder. -/
theorem conditionalSemiring_mul_le_mul_left
    {a b : ConditionalSemiring.{u}} (h : a ≤ b) (c : ConditionalSemiring.{u}) :
    c * a ≤ c * b := by
  calc
    c * a = a * c := mul_comm _ _
    _ ≤ b * c := conditionalSemiring_mul_le_mul_right h c
    _ = c * b := mul_comm _ _

/-- Multiplication is monotone in both variables. -/
theorem conditionalSemiring_mul_le_mul
    {a b c d : ConditionalSemiring.{u}} (hab : a ≤ b) (hcd : c ≤ d) :
    a * c ≤ b * d :=
  le_trans (conditionalSemiring_mul_le_mul_right hab c)
    (conditionalSemiring_mul_le_mul_left hcd b)

/-- Conditional mixing preserves total mass at every generating step. -/
theorem ConditionalOrderGenerator.mass_eq
    {a b : ConditionalSemiring.{u}} (h : ConditionalOrderGenerator a b) :
    conditionalSemiringMass a = conditionalSemiringMass b := by
  induction h with
  | channel P Q hPQ =>
      change jointConeMass P = jointConeMass Q
      exact hPQ.mass_eq.symm
  | add_right h c ih =>
      simpa only [conditionalSemiringMass_add] using
        congrArg (fun x : ℝ => x + conditionalSemiringMass c) ih
  | mul_right h c ih =>
      simpa only [conditionalSemiringMass_mul] using
        congrArg (fun x : ℝ => x * conditionalSemiringMass c) ih

/-- Comparable elements in the generated preorder have the same total mass,
as required by the manuscript's norm homomorphism. -/
theorem conditionalSemiringMass_eq_of_le
    {a b : ConditionalSemiring.{u}} (h : a ≤ b) :
    conditionalSemiringMass a = conditionalSemiringMass b := by
  change Relation.ReflTransGen ConditionalOrderGenerator a b at h
  induction h with
  | refl => rfl
  | tail h step ih => exact ih.trans step.mass_eq

/-- In particular, no nonzero element can lie below zero in the generated
conditional-majorization preorder. -/
theorem conditionalSemiring_eq_zero_of_le_zero
    {a : ConditionalSemiring.{u}} (h : a ≤ 0) : a = 0 := by
  apply (conditionalSemiringMass_eq_zero_iff a).mp
  simpa only [conditionalSemiringMass_zero] using
    (conditionalSemiringMass_eq_of_le h)

/-- The order-theoretic separation condition used in the manuscript's
definition of a preordered semidomain. -/
theorem conditionalSemiring_eq_zero_of_zero_le_of_le_zero
    {a : ConditionalSemiring.{u}} (_hzero : 0 ≤ a) (ha : a ≤ 0) : a = 0 :=
  conditionalSemiring_eq_zero_of_le_zero ha

/-- Restrict a real-valued quotient-semiring functional to normalized joint
distributions. -/
def semiringJointFunctional (f : ConditionalSemiring.{u} → ℝ) :
    PolyJointFunctional.{u} :=
  fun {_X _Y} _ _ _ _ P => f (conditionalSemiringOfJointProb P)

theorem semiringJointFunctional_embeddingInvariant
    (f : ConditionalSemiring.{u} → ℝ) :
    JointEmbeddingInvariant (semiringJointFunctional f) := by
  intro X Y X' Y' _ _ _ _ _ _ _ _ eX eY P
  exact congrArg f (conditionalSemiringOfJointProb_zeroExtend eX eY P)

theorem semiringJointFunctional_cmMonotone
    (f : ConditionalSemiring.{u} → ℝ) (hf : Monotone f) :
    CMMonotone (semiringJointFunctional f) := by
  intro X Y Y' _ _ _ _ _ _ P Q hPQ
  exact hf (conditionalSemiringOfJointProb_le hPQ)

/-- The quotient bridge and `embeddingLift` recover monotonicity under the
full embedded channel relation from semiring monotonicity. -/
theorem semiringJointFunctional_embeddingLift
    (f : ConditionalSemiring.{u} → ℝ) (hf : Monotone f) :
    CEmbedsMonotone (semiringJointFunctional f) :=
  embeddingLift _ (semiringJointFunctional_embeddingInvariant f)
    (semiringJointFunctional_cmMonotone f hf)

end ConditionalEntropy
