import ConditionalEntropy.FiniteSemiring
import Mathlib.Data.Quot

/-!
# The universe-safe finite-matrix quotient

The manuscript takes all finite nonnegative matrices, of every finite shape,
modulo relabelling and insertion/deletion of zero rows and columns.  A sigma
type over concrete dimensions would force arbitrary choices of enumerations.
Instead we store the finite row and column types themselves.  This produces a
single closed carrier one universe higher and lets direct sum and tensor use
`Sum` and `Prod` literally.

`FiniteJointStep` generates the least algebra congruence containing every zero
extension.  Its equivalence closure therefore includes relabellings (zero
extension along an equivalence), deletion of zero rows/columns, and all finite
zig-zags of these moves.  The quotient operations below are well-defined by
construction; no choice of representatives is exposed.
-/

namespace ConditionalEntropy

universe u

/-- One finite, unnormalised, nonnegative matrix with its finite alphabets. -/
structure FiniteJointRep where
  X : Type u
  Y : Type u
  fintypeX : Fintype X
  fintypeY : Fintype Y
  matrix : JointCone X Y

attribute [instance] FiniteJointRep.fintypeX FiniteJointRep.fintypeY

/-- Heterogeneous block sum as a closed operation. -/
@[reducible] def finiteJointAdd (P Q : FiniteJointRep.{u}) : FiniteJointRep.{u} where
  X := Sum P.X Q.X
  Y := Sum P.Y Q.Y
  fintypeX := inferInstance
  fintypeY := inferInstance
  matrix := jointConeDirectSum P.matrix Q.matrix

/-- Heterogeneous Kronecker product as a closed operation. -/
@[reducible] def finiteJointMul (P Q : FiniteJointRep.{u}) : FiniteJointRep.{u} where
  X := P.X × Q.X
  Y := P.Y × Q.Y
  fintypeX := inferInstance
  fintypeY := inferInstance
  matrix := jointConeTensor P.matrix Q.matrix

/-- Additive-zero representative. -/
def finiteJointZero : FiniteJointRep.{u} where
  X := ULift.{u} (Fin 1)
  Y := ULift.{u} (Fin 1)
  fintypeX := inferInstance
  fintypeY := inferInstance
  matrix := ⟨fun _ _ => 0, fun _ _ => le_rfl⟩

/-- Multiplicative-unit representative. -/
def finiteJointOne : FiniteJointRep.{u} where
  X := ULift.{u} (Fin 1)
  Y := ULift.{u} (Fin 1)
  fintypeX := inferInstance
  fintypeY := inferInstance
  matrix := ⟨fun _ _ => 1, fun _ _ => zero_le_one⟩

/-- Relabel a stored representative by equivalences. -/
def finiteJointRelabel (P : FiniteJointRep.{u})
    {X' Y' : Type u} [Fintype X'] [Fintype Y']
    (eX : P.X ≃ X') (eY : P.Y ≃ Y') : FiniteJointRep.{u} where
  X := X'
  Y := Y'
  fintypeX := inferInstance
  fintypeY := inferInstance
  matrix := jointConeRelabel eX eY P.matrix

/-- Insert zero rows and columns in a stored representative. -/
noncomputable def finiteJointZeroExtend (P : FiniteJointRep.{u})
    {X' Y' : Type u} [Fintype X'] [Fintype Y']
    (eX : P.X ↪ X') (eY : P.Y ↪ Y') : FiniteJointRep.{u} where
  X := X'
  Y := Y'
  fintypeX := inferInstance
  fintypeY := inferInstance
  matrix := jointConeZeroExtend eX eY P.matrix

/-- Total mass of a stored representative. -/
noncomputable def finiteJointMass (P : FiniteJointRep.{u}) : ℝ :=
  jointConeMass P.matrix

theorem finiteJointMass_add (P Q : FiniteJointRep.{u}) :
    finiteJointMass (finiteJointAdd P Q) = finiteJointMass P + finiteJointMass Q := by
  simp [finiteJointMass, finiteJointAdd, jointConeMass, jointConeDirectSum, add_comm]

theorem finiteJointMass_mul (P Q : FiniteJointRep.{u}) :
    finiteJointMass (finiteJointMul P Q) = finiteJointMass P * finiteJointMass Q := by
  simp only [finiteJointMass, finiteJointMul, jointConeMass, jointConeTensor_apply,
    Fintype.sum_prod_type]
  calc
    (∑ x, ∑ x', ∑ y, ∑ y', P.matrix x y * Q.matrix x' y') =
        ∑ x, ∑ x', (∑ y, P.matrix x y) * (∑ y', Q.matrix x' y') := by
      apply Finset.sum_congr rfl
      intro x _
      apply Finset.sum_congr rfl
      intro x' _
      rw [Finset.sum_mul]
      apply Finset.sum_congr rfl
      intro y _
      rw [Finset.mul_sum]
    _ = ∑ x, (∑ y, P.matrix x y) *
        (∑ x', ∑ y', Q.matrix x' y') := by
      apply Finset.sum_congr rfl
      intro x _
      rw [Finset.mul_sum]
    _ = (∑ x, ∑ y, P.matrix x y) *
        (∑ x', ∑ y', Q.matrix x' y') := by
      rw [Finset.sum_mul]

/-- The algebraic congruence generated by finite zero extensions. -/
inductive FiniteJointStep : FiniteJointRep.{u} → FiniteJointRep.{u} → Prop
  | zeroExtend (P : FiniteJointRep.{u})
      {X' Y' : Type u} [Fintype X'] [Fintype Y']
      (eX : P.X ↪ X') (eY : P.Y ↪ Y') :
      FiniteJointStep P (finiteJointZeroExtend P eX eY)
  | add_left {P Q : FiniteJointRep.{u}} (h : FiniteJointStep P Q)
      (R : FiniteJointRep.{u}) :
      FiniteJointStep (finiteJointAdd P R) (finiteJointAdd Q R)
  | add_right (P : FiniteJointRep.{u}) {Q R : FiniteJointRep.{u}}
      (h : FiniteJointStep Q R) :
      FiniteJointStep (finiteJointAdd P Q) (finiteJointAdd P R)
  | mul_left {P Q : FiniteJointRep.{u}} (h : FiniteJointStep P Q)
      (R : FiniteJointRep.{u}) :
      FiniteJointStep (finiteJointMul P R) (finiteJointMul Q R)
  | mul_right (P : FiniteJointRep.{u}) {Q R : FiniteJointRep.{u}}
      (h : FiniteJointStep Q R) :
      FiniteJointStep (finiteJointMul P Q) (finiteJointMul P R)

/-- Similarity is the equivalence closure of zero extension and its algebra
congruence rules. -/
def FiniteJointSimilar : FiniteJointRep.{u} → FiniteJointRep.{u} → Prop :=
  Relation.EqvGen FiniteJointStep

/-- Zero extension along equivalences agrees with representative relabelling. -/
theorem finiteJointZeroExtend_equiv (P : FiniteJointRep.{u})
    {X' Y' : Type u} [Fintype X'] [Fintype Y']
    (eX : P.X ≃ X') (eY : P.Y ≃ Y') :
    finiteJointZeroExtend P eX.toEmbedding eY.toEmbedding =
      finiteJointRelabel P eX eY := by
  cases P with
  | mk X Y fintypeX fintypeY matrix =>
      simp only [finiteJointZeroExtend, finiteJointRelabel]
      congr 1
      exact jointConeZeroExtend_equiv eX eY matrix

theorem finiteJointAdd_comm_relabel (P Q : FiniteJointRep.{u}) :
    finiteJointRelabel (finiteJointAdd P Q)
        (Equiv.sumComm P.X Q.X) (Equiv.sumComm P.Y Q.Y) =
      finiteJointAdd Q P := by
  cases P with
  | mk X Y fintypeX fintypeY matrixP =>
    cases Q with
    | mk X' Y' fintypeX' fintypeY' matrixQ =>
      simp only [finiteJointRelabel, finiteJointAdd]
      congr 1
      exact jointConeDirectSum_comm_relabel matrixP matrixQ

theorem finiteJointAdd_assoc_relabel (P Q R : FiniteJointRep.{u}) :
    finiteJointRelabel (finiteJointAdd (finiteJointAdd P Q) R)
        (Equiv.sumAssoc P.X Q.X R.X) (Equiv.sumAssoc P.Y Q.Y R.Y) =
      finiteJointAdd P (finiteJointAdd Q R) := by
  cases P with
  | mk X₁ Y₁ fintypeX₁ fintypeY₁ matrixP =>
    cases Q with
    | mk X₂ Y₂ fintypeX₂ fintypeY₂ matrixQ =>
      cases R with
      | mk X₃ Y₃ fintypeX₃ fintypeY₃ matrixR =>
        simp only [finiteJointRelabel, finiteJointAdd]
        congr 1
        exact jointConeDirectSum_assoc_relabel matrixP matrixQ matrixR

theorem finiteJointMul_comm_relabel (P Q : FiniteJointRep.{u}) :
    finiteJointRelabel (finiteJointMul P Q)
        (Equiv.prodComm P.X Q.X) (Equiv.prodComm P.Y Q.Y) =
      finiteJointMul Q P := by
  cases P with
  | mk X Y fintypeX fintypeY matrixP =>
    cases Q with
    | mk X' Y' fintypeX' fintypeY' matrixQ =>
      simp only [finiteJointRelabel, finiteJointMul]
      congr 1
      exact jointConeTensor_comm_relabel matrixP matrixQ

theorem finiteJointMul_assoc_relabel (P Q R : FiniteJointRep.{u}) :
    finiteJointRelabel (finiteJointMul (finiteJointMul P Q) R)
        (Equiv.prodAssoc P.X Q.X R.X) (Equiv.prodAssoc P.Y Q.Y R.Y) =
      finiteJointMul P (finiteJointMul Q R) := by
  cases P with
  | mk X₁ Y₁ fintypeX₁ fintypeY₁ matrixP =>
    cases Q with
    | mk X₂ Y₂ fintypeX₂ fintypeY₂ matrixQ =>
      cases R with
      | mk X₃ Y₃ fintypeX₃ fintypeY₃ matrixR =>
        simp only [finiteJointRelabel, finiteJointMul]
        congr 1
        exact jointConeTensor_assoc_relabel matrixP matrixQ matrixR

theorem finiteJointMul_add_left_relabel (P Q R : FiniteJointRep.{u}) :
    finiteJointRelabel (finiteJointMul (finiteJointAdd P Q) R)
        (Equiv.sumProdDistrib P.X Q.X R.X)
        (Equiv.sumProdDistrib P.Y Q.Y R.Y) =
      finiteJointAdd (finiteJointMul P R) (finiteJointMul Q R) := by
  cases P with
  | mk X₁ Y₁ fintypeX₁ fintypeY₁ matrixP =>
    cases Q with
    | mk X₂ Y₂ fintypeX₂ fintypeY₂ matrixQ =>
      cases R with
      | mk X₃ Y₃ fintypeX₃ fintypeY₃ matrixR =>
        simp only [finiteJointRelabel, finiteJointMul, finiteJointAdd]
        congr 1
        exact jointConeTensor_directSum_left_relabel matrixP matrixQ matrixR

theorem finiteJointMul_add_right_relabel (P Q R : FiniteJointRep.{u}) :
    finiteJointRelabel (finiteJointMul P (finiteJointAdd Q R))
        (Equiv.prodSumDistrib P.X Q.X R.X)
        (Equiv.prodSumDistrib P.Y Q.Y R.Y) =
      finiteJointAdd (finiteJointMul P Q) (finiteJointMul P R) := by
  cases P with
  | mk X₁ Y₁ fintypeX₁ fintypeY₁ matrixP =>
    cases Q with
    | mk X₂ Y₂ fintypeX₂ fintypeY₂ matrixQ =>
      cases R with
      | mk X₃ Y₃ fintypeX₃ fintypeY₃ matrixR =>
        simp only [finiteJointRelabel, finiteJointMul, finiteJointAdd]
        congr 1
        exact jointConeTensor_directSum_right_relabel matrixP matrixQ matrixR

/-- Adding the chosen zero representative is a zero extension. -/
theorem finiteJointZeroExtend_sumInl (P : FiniteJointRep.{u}) :
    finiteJointZeroExtend P (sumInlEmbedding P.X finiteJointZero.X)
        (sumInlEmbedding P.Y finiteJointZero.Y) =
      finiteJointAdd P finiteJointZero := by
  cases P with
  | mk X Y fintypeX fintypeY matrix =>
      simp only [finiteJointZeroExtend, finiteJointAdd, finiteJointZero]
      congr 1
      exact jointConeZeroExtend_sumInl matrix

/-- A product with the singleton alphabet is canonically equivalent to the
original alphabet. -/
def prodULiftFinOneEquiv (X : Type u) : X × ULift.{u} (Fin 1) ≃ X where
  toFun := Prod.fst
  invFun := fun x => (x, ⟨⟨0, by norm_num⟩⟩)
  left_inv := by
    intro x
    apply Prod.ext
    · rfl
    · exact Subsingleton.elim _ _
  right_inv := by intro x; rfl

/-- Multiplication by the chosen unit is relabelling by the singleton-product
equivalence. -/
theorem finiteJointMul_one_relabel (P : FiniteJointRep.{u}) :
    finiteJointRelabel (finiteJointMul P finiteJointOne)
        (prodULiftFinOneEquiv P.X) (prodULiftFinOneEquiv P.Y) = P := by
  cases P with
  | mk X Y fintypeX fintypeY matrix =>
      simp only [finiteJointRelabel, finiteJointMul, finiteJointOne]
      congr 1
      apply Subtype.ext
      funext x y
      change matrix x y * 1 = matrix x y
      exact mul_one _

/-- A representative is pointwise zero. -/
def FiniteJointRep.IsZero (P : FiniteJointRep.{u}) : Prop :=
  ∀ x y, P.matrix x y = 0

theorem finiteJointMass_nonneg (P : FiniteJointRep.{u}) :
    0 ≤ finiteJointMass P :=
  Finset.sum_nonneg fun x _ => Finset.sum_nonneg fun y _ => P.matrix.2 x y

theorem finiteJointMass_eq_zero_iff (P : FiniteJointRep.{u}) :
    finiteJointMass P = 0 ↔ P.IsZero := by
  constructor
  · intro hmass x y
    have hrows : (fun x => ∑ y, P.matrix x y) = 0 :=
      (Fintype.sum_eq_zero_iff_of_nonneg
        (fun x => Finset.sum_nonneg fun y _ => P.matrix.2 x y)).mp hmass
    have hrow : (∑ y, P.matrix x y) = 0 := congrFun hrows x
    have hentries : (fun y => P.matrix x y) = 0 :=
      (Fintype.sum_eq_zero_iff_of_nonneg (P.matrix.2 x)).mp hrow
    exact congrFun hentries y
  · intro hzero
    change ∑ x, ∑ y, P.matrix x y = 0
    apply Finset.sum_eq_zero
    intro x hx
    apply Finset.sum_eq_zero
    intro y hy
    exact hzero x y

theorem finiteJointZero_isZero : finiteJointZero.IsZero := by
  intro x y
  rfl

theorem finiteJointMul_zero_isZero (P : FiniteJointRep.{u}) :
    (finiteJointMul P finiteJointZero).IsZero := by
  intro x y
  change P.matrix x.1 y.1 * 0 = 0
  exact mul_zero _

/-- Any two pointwise-zero representatives have equal zero extensions into
the disjoint union of their alphabets. -/
theorem finiteJointZeroExtensions_eq (P Q : FiniteJointRep.{u})
    (hP : P.IsZero) (hQ : Q.IsZero) :
    finiteJointZeroExtend P (sumInlEmbedding P.X Q.X)
        (sumInlEmbedding P.Y Q.Y) =
      finiteJointZeroExtend Q (sumInrEmbedding P.X Q.X)
        (sumInrEmbedding P.Y Q.Y) := by
  cases P with
  | mk X Y fintypeX fintypeY matrixP =>
    cases Q with
    | mk X' Y' fintypeX' fintypeY' matrixQ =>
      simp only [finiteJointZeroExtend]
      congr 1
      rw [jointConeZeroExtend_eq_zero _ _ matrixP hP,
        jointConeZeroExtend_eq_zero _ _ matrixQ hQ]

/-- The closed quotient carrier underlying the manuscript's finite-matrix
semiring. -/
abbrev ConditionalSemiring := Quot (@FiniteJointStep.{u})

/-- Insert a representative into the quotient. -/
def ConditionalSemiring.mk (P : FiniteJointRep.{u}) : ConditionalSemiring.{u} :=
  Quot.mk _ P

instance conditionalSemiringAdd : Add ConditionalSemiring.{u} where
  add := Quot.map₂ finiteJointAdd
    (fun P _ _ h => FiniteJointStep.add_right P h)
    (fun _ _ Q h => FiniteJointStep.add_left h Q)

instance conditionalSemiringMul : Mul ConditionalSemiring.{u} where
  mul := Quot.map₂ finiteJointMul
    (fun P _ _ h => FiniteJointStep.mul_right P h)
    (fun _ _ Q h => FiniteJointStep.mul_left h Q)

instance conditionalSemiringZero : Zero ConditionalSemiring.{u} :=
  ⟨ConditionalSemiring.mk finiteJointZero⟩
instance conditionalSemiringOne : One ConditionalSemiring.{u} :=
  ⟨ConditionalSemiring.mk finiteJointOne⟩

@[simp] theorem ConditionalSemiring.mk_add (P Q : FiniteJointRep.{u}) :
    ConditionalSemiring.mk P + ConditionalSemiring.mk Q =
      ConditionalSemiring.mk (finiteJointAdd P Q) := rfl

@[simp] theorem ConditionalSemiring.mk_mul (P Q : FiniteJointRep.{u}) :
    ConditionalSemiring.mk P * ConditionalSemiring.mk Q =
      ConditionalSemiring.mk (finiteJointMul P Q) := rfl

/-- Quotient equality is precisely a finite zig-zag of zero extensions and
the congruence rules. -/
theorem ConditionalSemiring.mk_eq_mk_iff (P Q : FiniteJointRep.{u}) :
    ConditionalSemiring.mk P = ConditionalSemiring.mk Q ↔ FiniteJointSimilar P Q :=
  ⟨Quot.eqvGen_exact, Quot.eqvGen_sound⟩

/-- Relabelled representatives define the same quotient element. -/
theorem ConditionalSemiring.mk_relabel (P : FiniteJointRep.{u})
    {X' Y' : Type u} [Fintype X'] [Fintype Y']
    (eX : P.X ≃ X') (eY : P.Y ≃ Y') :
    ConditionalSemiring.mk (finiteJointRelabel P eX eY) =
      ConditionalSemiring.mk P := by
  apply Quot.eqvGen_sound
  exact Relation.EqvGen.symm _ _
    (Relation.EqvGen.rel _ _ (finiteJointZeroExtend_equiv P eX eY ▸
      FiniteJointStep.zeroExtend P eX.toEmbedding eY.toEmbedding))

/-- Every pointwise-zero representative denotes the same quotient element. -/
theorem ConditionalSemiring.mk_eq_of_isZero (P Q : FiniteJointRep.{u})
    (hP : P.IsZero) (hQ : Q.IsZero) :
    ConditionalSemiring.mk P = ConditionalSemiring.mk Q := by
  calc
    ConditionalSemiring.mk P =
        ConditionalSemiring.mk
          (finiteJointZeroExtend P (sumInlEmbedding P.X Q.X)
            (sumInlEmbedding P.Y Q.Y)) :=
      Quot.sound (FiniteJointStep.zeroExtend P
        (sumInlEmbedding P.X Q.X) (sumInlEmbedding P.Y Q.Y))
    _ = ConditionalSemiring.mk
        (finiteJointZeroExtend Q (sumInrEmbedding P.X Q.X)
          (sumInrEmbedding P.Y Q.Y)) :=
      congrArg ConditionalSemiring.mk (finiteJointZeroExtensions_eq P Q hP hQ)
    _ = ConditionalSemiring.mk Q :=
      (Quot.sound (FiniteJointStep.zeroExtend Q
        (sumInrEmbedding P.X Q.X) (sumInrEmbedding P.Y Q.Y))).symm

/-- Canonical block exchange becomes commutativity in the quotient. -/
theorem ConditionalSemiring.mk_add_comm (P Q : FiniteJointRep.{u}) :
    ConditionalSemiring.mk (finiteJointAdd P Q) =
      ConditionalSemiring.mk (finiteJointAdd Q P) := by
  calc
    ConditionalSemiring.mk (finiteJointAdd P Q) =
        ConditionalSemiring.mk
          (finiteJointRelabel (finiteJointAdd P Q)
            (Equiv.sumComm P.X Q.X) (Equiv.sumComm P.Y Q.Y)) :=
      (ConditionalSemiring.mk_relabel (finiteJointAdd P Q)
        (Equiv.sumComm P.X Q.X) (Equiv.sumComm P.Y Q.Y)).symm
    _ = ConditionalSemiring.mk (finiteJointAdd Q P) :=
      congrArg ConditionalSemiring.mk (finiteJointAdd_comm_relabel P Q)

/-- Canonical reassociation becomes additive associativity in the quotient. -/
theorem ConditionalSemiring.mk_add_assoc (P Q R : FiniteJointRep.{u}) :
    ConditionalSemiring.mk (finiteJointAdd (finiteJointAdd P Q) R) =
      ConditionalSemiring.mk (finiteJointAdd P (finiteJointAdd Q R)) := by
  calc
    ConditionalSemiring.mk (finiteJointAdd (finiteJointAdd P Q) R) =
        ConditionalSemiring.mk
          (finiteJointRelabel (finiteJointAdd (finiteJointAdd P Q) R)
            (Equiv.sumAssoc P.X Q.X R.X) (Equiv.sumAssoc P.Y Q.Y R.Y)) :=
      (ConditionalSemiring.mk_relabel (finiteJointAdd (finiteJointAdd P Q) R)
        (Equiv.sumAssoc P.X Q.X R.X) (Equiv.sumAssoc P.Y Q.Y R.Y)).symm
    _ = ConditionalSemiring.mk (finiteJointAdd P (finiteJointAdd Q R)) :=
      congrArg ConditionalSemiring.mk (finiteJointAdd_assoc_relabel P Q R)

/-- Canonical factor exchange becomes commutativity in the quotient. -/
theorem ConditionalSemiring.mk_mul_comm (P Q : FiniteJointRep.{u}) :
    ConditionalSemiring.mk (finiteJointMul P Q) =
      ConditionalSemiring.mk (finiteJointMul Q P) := by
  calc
    ConditionalSemiring.mk (finiteJointMul P Q) =
        ConditionalSemiring.mk
          (finiteJointRelabel (finiteJointMul P Q)
            (Equiv.prodComm P.X Q.X) (Equiv.prodComm P.Y Q.Y)) :=
      (ConditionalSemiring.mk_relabel (finiteJointMul P Q)
        (Equiv.prodComm P.X Q.X) (Equiv.prodComm P.Y Q.Y)).symm
    _ = ConditionalSemiring.mk (finiteJointMul Q P) :=
      congrArg ConditionalSemiring.mk (finiteJointMul_comm_relabel P Q)

/-- Canonical reassociation becomes multiplicative associativity in the
quotient. -/
theorem ConditionalSemiring.mk_mul_assoc (P Q R : FiniteJointRep.{u}) :
    ConditionalSemiring.mk (finiteJointMul (finiteJointMul P Q) R) =
      ConditionalSemiring.mk (finiteJointMul P (finiteJointMul Q R)) := by
  calc
    ConditionalSemiring.mk (finiteJointMul (finiteJointMul P Q) R) =
        ConditionalSemiring.mk
          (finiteJointRelabel (finiteJointMul (finiteJointMul P Q) R)
            (Equiv.prodAssoc P.X Q.X R.X) (Equiv.prodAssoc P.Y Q.Y R.Y)) :=
      (ConditionalSemiring.mk_relabel (finiteJointMul (finiteJointMul P Q) R)
        (Equiv.prodAssoc P.X Q.X R.X) (Equiv.prodAssoc P.Y Q.Y R.Y)).symm
    _ = ConditionalSemiring.mk (finiteJointMul P (finiteJointMul Q R)) :=
      congrArg ConditionalSemiring.mk (finiteJointMul_assoc_relabel P Q R)

/-- Left distribution holds after the canonical sum-product relabelling. -/
theorem ConditionalSemiring.mk_mul_add_left (P Q R : FiniteJointRep.{u}) :
    ConditionalSemiring.mk (finiteJointMul (finiteJointAdd P Q) R) =
      ConditionalSemiring.mk
        (finiteJointAdd (finiteJointMul P R) (finiteJointMul Q R)) := by
  calc
    ConditionalSemiring.mk (finiteJointMul (finiteJointAdd P Q) R) =
        ConditionalSemiring.mk
          (finiteJointRelabel (finiteJointMul (finiteJointAdd P Q) R)
            (Equiv.sumProdDistrib P.X Q.X R.X)
            (Equiv.sumProdDistrib P.Y Q.Y R.Y)) :=
      (ConditionalSemiring.mk_relabel (finiteJointMul (finiteJointAdd P Q) R)
        (Equiv.sumProdDistrib P.X Q.X R.X)
        (Equiv.sumProdDistrib P.Y Q.Y R.Y)).symm
    _ = ConditionalSemiring.mk
        (finiteJointAdd (finiteJointMul P R) (finiteJointMul Q R)) :=
      congrArg ConditionalSemiring.mk (finiteJointMul_add_left_relabel P Q R)

/-- Right distribution holds after the canonical product-sum relabelling. -/
theorem ConditionalSemiring.mk_mul_add_right (P Q R : FiniteJointRep.{u}) :
    ConditionalSemiring.mk (finiteJointMul P (finiteJointAdd Q R)) =
      ConditionalSemiring.mk
        (finiteJointAdd (finiteJointMul P Q) (finiteJointMul P R)) := by
  calc
    ConditionalSemiring.mk (finiteJointMul P (finiteJointAdd Q R)) =
        ConditionalSemiring.mk
          (finiteJointRelabel (finiteJointMul P (finiteJointAdd Q R))
            (Equiv.prodSumDistrib P.X Q.X R.X)
            (Equiv.prodSumDistrib P.Y Q.Y R.Y)) :=
      (ConditionalSemiring.mk_relabel (finiteJointMul P (finiteJointAdd Q R))
        (Equiv.prodSumDistrib P.X Q.X R.X)
        (Equiv.prodSumDistrib P.Y Q.Y R.Y)).symm
    _ = ConditionalSemiring.mk
        (finiteJointAdd (finiteJointMul P Q) (finiteJointMul P R)) :=
      congrArg ConditionalSemiring.mk (finiteJointMul_add_right_relabel P Q R)

/-- The selected all-zero singleton is an additive right identity. -/
theorem ConditionalSemiring.mk_add_zero (P : FiniteJointRep.{u}) :
    ConditionalSemiring.mk (finiteJointAdd P finiteJointZero) =
      ConditionalSemiring.mk P := by
  calc
    ConditionalSemiring.mk (finiteJointAdd P finiteJointZero) =
        ConditionalSemiring.mk
          (finiteJointZeroExtend P (sumInlEmbedding P.X finiteJointZero.X)
            (sumInlEmbedding P.Y finiteJointZero.Y)) :=
      congrArg ConditionalSemiring.mk (finiteJointZeroExtend_sumInl P).symm
    _ = ConditionalSemiring.mk P :=
      (Quot.sound (FiniteJointStep.zeroExtend P
        (sumInlEmbedding P.X finiteJointZero.X)
        (sumInlEmbedding P.Y finiteJointZero.Y))).symm

/-- The selected singleton point mass is a multiplicative right identity. -/
theorem ConditionalSemiring.mk_mul_one (P : FiniteJointRep.{u}) :
    ConditionalSemiring.mk (finiteJointMul P finiteJointOne) =
      ConditionalSemiring.mk P := by
  calc
    ConditionalSemiring.mk (finiteJointMul P finiteJointOne) =
        ConditionalSemiring.mk
          (finiteJointRelabel (finiteJointMul P finiteJointOne)
            (prodULiftFinOneEquiv P.X) (prodULiftFinOneEquiv P.Y)) :=
      (ConditionalSemiring.mk_relabel (finiteJointMul P finiteJointOne)
        (prodULiftFinOneEquiv P.X) (prodULiftFinOneEquiv P.Y)).symm
    _ = ConditionalSemiring.mk P :=
      congrArg ConditionalSemiring.mk (finiteJointMul_one_relabel P)

/-- The selected zero annihilates multiplication on the right. -/
theorem ConditionalSemiring.mk_mul_zero (P : FiniteJointRep.{u}) :
    ConditionalSemiring.mk (finiteJointMul P finiteJointZero) =
      ConditionalSemiring.mk finiteJointZero :=
  ConditionalSemiring.mk_eq_of_isZero _ _
    (finiteJointMul_zero_isZero P) finiteJointZero_isZero

theorem conditionalSemiring_add_assoc
    (a b c : ConditionalSemiring.{u}) : (a + b) + c = a + (b + c) := by
  induction a using Quot.ind with
  | _ P =>
    induction b using Quot.ind with
    | _ Q =>
      induction c using Quot.ind with
      | _ R => exact ConditionalSemiring.mk_add_assoc P Q R

theorem conditionalSemiring_add_comm
    (a b : ConditionalSemiring.{u}) : a + b = b + a := by
  induction a using Quot.ind with
  | _ P =>
    induction b using Quot.ind with
    | _ Q => exact ConditionalSemiring.mk_add_comm P Q

theorem conditionalSemiring_add_zero
    (a : ConditionalSemiring.{u}) : a + 0 = a := by
  induction a using Quot.ind with
  | _ P => exact ConditionalSemiring.mk_add_zero P

theorem conditionalSemiring_zero_add
    (a : ConditionalSemiring.{u}) : 0 + a = a := by
  rw [conditionalSemiring_add_comm, conditionalSemiring_add_zero]

theorem conditionalSemiring_mul_assoc
    (a b c : ConditionalSemiring.{u}) : (a * b) * c = a * (b * c) := by
  induction a using Quot.ind with
  | _ P =>
    induction b using Quot.ind with
    | _ Q =>
      induction c using Quot.ind with
      | _ R => exact ConditionalSemiring.mk_mul_assoc P Q R

theorem conditionalSemiring_mul_comm
    (a b : ConditionalSemiring.{u}) : a * b = b * a := by
  induction a using Quot.ind with
  | _ P =>
    induction b using Quot.ind with
    | _ Q => exact ConditionalSemiring.mk_mul_comm P Q

theorem conditionalSemiring_mul_one
    (a : ConditionalSemiring.{u}) : a * 1 = a := by
  induction a using Quot.ind with
  | _ P => exact ConditionalSemiring.mk_mul_one P

theorem conditionalSemiring_one_mul
    (a : ConditionalSemiring.{u}) : 1 * a = a := by
  rw [conditionalSemiring_mul_comm, conditionalSemiring_mul_one]

theorem conditionalSemiring_mul_zero
    (a : ConditionalSemiring.{u}) : a * 0 = 0 := by
  induction a using Quot.ind with
  | _ P => exact ConditionalSemiring.mk_mul_zero P

theorem conditionalSemiring_zero_mul
    (a : ConditionalSemiring.{u}) : 0 * a = 0 := by
  rw [conditionalSemiring_mul_comm, conditionalSemiring_mul_zero]

theorem conditionalSemiring_left_distrib
    (a b c : ConditionalSemiring.{u}) : a * (b + c) = a * b + a * c := by
  induction a using Quot.ind with
  | _ P =>
    induction b using Quot.ind with
    | _ Q =>
      induction c using Quot.ind with
      | _ R => exact ConditionalSemiring.mk_mul_add_right P Q R

theorem conditionalSemiring_right_distrib
    (a b c : ConditionalSemiring.{u}) : (a + b) * c = a * c + b * c := by
  induction a using Quot.ind with
  | _ P =>
    induction b using Quot.ind with
    | _ Q =>
      induction c using Quot.ind with
      | _ R => exact ConditionalSemiring.mk_mul_add_left P Q R

/-- The manuscript's direct sum and tensor product form a genuine commutative
semiring after quotienting by relabelling and zero insertion/deletion. -/
instance conditionalSemiringCommSemiring : CommSemiring ConditionalSemiring.{u} where
  add := conditionalSemiringAdd.add
  zero := conditionalSemiringZero.zero
  mul := conditionalSemiringMul.mul
  one := conditionalSemiringOne.one
  nsmul := nsmulRec
  add_assoc := conditionalSemiring_add_assoc
  zero_add := conditionalSemiring_zero_add
  add_zero := conditionalSemiring_add_zero
  add_comm := conditionalSemiring_add_comm
  mul_assoc := conditionalSemiring_mul_assoc
  one_mul := conditionalSemiring_one_mul
  mul_one := conditionalSemiring_mul_one
  left_distrib := conditionalSemiring_left_distrib
  right_distrib := conditionalSemiring_right_distrib
  zero_mul := conditionalSemiring_zero_mul
  mul_zero := conditionalSemiring_mul_zero
  mul_comm := conditionalSemiring_mul_comm

/-- Every generator preserves total mass. -/
theorem FiniteJointStep.mass_eq {P Q : FiniteJointRep.{u}}
    (h : FiniteJointStep P Q) : finiteJointMass P = finiteJointMass Q := by
  induction h with
  | zeroExtend P eX eY =>
      exact (jointConeMass_zeroExtend eX eY P.matrix).symm
  | add_left h R ih =>
      rw [finiteJointMass_add, finiteJointMass_add]
      exact congrArg (fun x : ℝ => x + finiteJointMass R) ih
  | add_right P h ih =>
      rw [finiteJointMass_add, finiteJointMass_add]
      exact congrArg (fun x : ℝ => finiteJointMass P + x) ih
  | mul_left h R ih =>
      rw [finiteJointMass_mul, finiteJointMass_mul]
      exact congrArg (fun x : ℝ => x * finiteJointMass R) ih
  | mul_right P h ih =>
      rw [finiteJointMass_mul, finiteJointMass_mul]
      exact congrArg (fun x : ℝ => finiteJointMass P * x) ih

/-- Total mass descends to the zero-extension quotient. -/
noncomputable def conditionalSemiringMass : ConditionalSemiring.{u} → ℝ :=
  Quot.lift finiteJointMass (fun _ _ h => FiniteJointStep.mass_eq h)

@[simp] theorem conditionalSemiringMass_mk (P : FiniteJointRep.{u}) :
    conditionalSemiringMass (ConditionalSemiring.mk P) = finiteJointMass P := rfl

@[simp] theorem conditionalSemiringMass_add (a b : ConditionalSemiring.{u}) :
    conditionalSemiringMass (a + b) =
      conditionalSemiringMass a + conditionalSemiringMass b := by
  induction a using Quot.ind with
  | _ P =>
    induction b using Quot.ind with
    | _ Q => exact jointConeMass_directSum P.matrix Q.matrix

@[simp] theorem conditionalSemiringMass_mul (a b : ConditionalSemiring.{u}) :
    conditionalSemiringMass (a * b) =
      conditionalSemiringMass a * conditionalSemiringMass b := by
  induction a using Quot.ind with
  | _ P =>
    induction b using Quot.ind with
    | _ Q => exact jointConeMass_tensor P.matrix Q.matrix

@[simp] theorem conditionalSemiringMass_zero :
    conditionalSemiringMass (0 : ConditionalSemiring.{u}) = 0 := by
  change finiteJointMass finiteJointZero = 0
  simp [finiteJointMass, finiteJointZero, jointConeMass]

@[simp] theorem conditionalSemiringMass_one :
    conditionalSemiringMass (1 : ConditionalSemiring.{u}) = 1 := by
  change finiteJointMass finiteJointOne = 1
  simp [finiteJointMass, finiteJointOne, jointConeMass]

theorem conditionalSemiringMass_nonneg (a : ConditionalSemiring.{u}) :
    0 ≤ conditionalSemiringMass a := by
  induction a using Quot.ind with
  | _ P => exact finiteJointMass_nonneg P

theorem conditionalSemiringMass_eq_zero_iff (a : ConditionalSemiring.{u}) :
    conditionalSemiringMass a = 0 ↔ a = 0 := by
  induction a using Quot.ind with
  | _ P =>
    constructor
    · intro hmass
      exact ConditionalSemiring.mk_eq_of_isZero P finiteJointZero
        ((finiteJointMass_eq_zero_iff P).mp hmass) finiteJointZero_isZero
    · intro hzero
      rw [hzero, conditionalSemiringMass_zero]

/-- Total mass is a semiring homomorphism with trivial kernel. -/
noncomputable def conditionalSemiringMassHom : ConditionalSemiring.{u} →+* ℝ where
  toFun := conditionalSemiringMass
  map_zero' := conditionalSemiringMass_zero
  map_one' := conditionalSemiringMass_one
  map_add' := conditionalSemiringMass_add
  map_mul' := conditionalSemiringMass_mul

instance conditionalSemiringNontrivial : Nontrivial ConditionalSemiring.{u} := by
  refine ⟨⟨0, 1, ?_⟩⟩
  intro h
  have hmass := congrArg conditionalSemiringMass h
  norm_num at hmass

instance conditionalSemiringNoZeroDivisors :
    NoZeroDivisors ConditionalSemiring.{u} where
  eq_zero_or_eq_zero_of_mul_eq_zero := by
    intro a b hab
    have hmass : conditionalSemiringMass a * conditionalSemiringMass b = 0 := by
      rw [← conditionalSemiringMass_mul, hab, conditionalSemiringMass_zero]
    rcases mul_eq_zero.mp hmass with ha | hb
    · exact Or.inl ((conditionalSemiringMass_eq_zero_iff a).mp ha)
    · exact Or.inr ((conditionalSemiringMass_eq_zero_iff b).mp hb)

/-- The quotient is zerosumfree. -/
theorem conditionalSemiring_eq_zero_of_add_eq_zero
    {a b : ConditionalSemiring.{u}} (h : a + b = 0) : a = 0 ∧ b = 0 := by
  have hmass : conditionalSemiringMass a + conditionalSemiringMass b = 0 := by
    rw [← conditionalSemiringMass_add, h, conditionalSemiringMass_zero]
  have ha : conditionalSemiringMass a = 0 := by
    nlinarith [conditionalSemiringMass_nonneg a, conditionalSemiringMass_nonneg b]
  have hb : conditionalSemiringMass b = 0 := by
    nlinarith [conditionalSemiringMass_nonneg a, conditionalSemiringMass_nonneg b]
  exact ⟨(conditionalSemiringMass_eq_zero_iff a).mp ha,
    (conditionalSemiringMass_eq_zero_iff b).mp hb⟩

end ConditionalEntropy
