import CompleteCharacterization
import Mathlib.Util.AssertNoSorry

#print axioms ConditionalEntropy.continuousOn_entropyLine_full_bundle
#print axioms ConditionalEntropy.exactDerivatives
#print axioms ConditionalEntropy.hessianSignCriterion
#print axioms ConditionalEntropy.parameterizedRemovableShannonQuotient
#print axioms ConditionalEntropy.twoBlockLocalization
#print axioms ConditionalEntropy.threeBlockLocalization
#print axioms ConditionalEntropy.shannonLocalization
#print axioms ConditionalEntropy.positiveNecessity
#print axioms ConditionalEntropy.negativeTemperateNecessity
#print axioms ConditionalEntropy.negativeTropicalNecessity
#print axioms ConditionalEntropy.positiveTropicalNecessity
#print axioms ConditionalEntropy.derivationNecessity
#print axioms ConditionalEntropy.finiteTSufficiency
#print axioms ConditionalEntropy.negativeTropicalSufficiency
#print axioms ConditionalEntropy.positiveTropicalSufficiency
#print axioms ConditionalEntropy.derivationSufficiency
#print axioms ConditionalEntropy.embeddingLift
#print axioms ConditionalEntropy.semiringJointFunctional_embeddingLift
#print axioms ConditionalEntropy.necessityBundle
#print axioms ConditionalEntropy.mainClassification
#print axioms ConditionalEntropy.allConditionalEntropyAxioms

assert_no_sorry ConditionalEntropy.fullDetailsLemma4_1
assert_no_sorry ConditionalEntropy.fullDetailsLemma4_2
assert_no_sorry ConditionalEntropy.fullDetailsLemma4_3
assert_no_sorry ConditionalEntropy.fullDetailsProposition4_4
assert_no_sorry ConditionalEntropy.fullDetailsProposition4_5
assert_no_sorry ConditionalEntropy.fullDetailsProposition4_6
assert_no_sorry ConditionalEntropy.fullDetailsProposition4_7
assert_no_sorry ConditionalEntropy.fullDetailsProposition5_1
assert_no_sorry ConditionalEntropy.fullDetailsProposition5_2
assert_no_sorry ConditionalEntropy.fullDetailsProposition5_3
assert_no_sorry ConditionalEntropy.fullDetailsRemark5_4
assert_no_sorry ConditionalEntropy.fullDetailsRemark5_5
assert_no_sorry ConditionalEntropy.fullDetailsProposition5_6
assert_no_sorry ConditionalEntropy.fullDetailsProposition5_7
assert_no_sorry ConditionalEntropy.fullDetailsProposition5_8
assert_no_sorry ConditionalEntropy.fullDetailsProposition5_9
assert_no_sorry ConditionalEntropy.fullDetailsProposition5_10
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_1
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_2
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_3
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_4
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_5
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_6
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_7
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_8
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_9
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_10
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_11
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_12
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_13
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_14
assert_no_sorry ConditionalEntropy.fullDetailsAppendixA_15

#print axioms ConditionalEntropy.fullDetailsProposition5_10
#print axioms ConditionalEntropy.fullDetailsAppendixA_3
#print axioms ConditionalEntropy.fullDetailsAppendixA_6
#print axioms ConditionalEntropy.fullDetailsAppendixA_9
#print axioms ConditionalEntropy.fullDetailsAppendixA_11
